export const ROLES = {
  STUDENT: "student",
  PARENT: "parent",
  TEACHER: "teacher",
  ADMIN: "admin",
  SUPERADMIN: "superadmin",
};

export const ROLE_PERMISSIONS = {
  student: [
    "dashboard",
    "attendance",
    "syllabus",
    "timetable",
    "assignments",
     "fees",
    "library",
    "transport",
    "hostel",
    "result",
    "notice",
    "announcement",
    "profile",
    
  ],

  parent: [
    "dashboard",
    "attendance",
    "result",
    "fees",
    "notice",
     "announcement",
       "profile",
  ],

  teacher: [
    "dashboard",
    "students",
    "attendance",
    "syllabus",
    "timetable",
    "assignments",
    "result",
    "announcement",
    "fees",
    "library",
    "transport",
    "hostel",
      "profile",
  ],

  admin: [
    "dashboard",
    "students",
    "teachers",
     "departments",
  "department-list",
    "user-management",
    "roles-permissions",
    "announcement",
    "notice",
    "fees",
    "library",
    "transport",
    "hostel",
   "users",
  "user-create",
  "user-list",
    "reports",
      "profile",
  ],

  superadmin: [
     "dashboard",
  "departments",
  "users",
  "user-create",
  "user-list",
  "department-list",
  "department-create",
  "user-management",
  "roles-permissions",
  "reports",
  "billing",
  "audit",
  "organizations",
  "approvals",
  "settings",
  "admins",
  "students",
  "teachers",
  "announcement",
  "notice",
  "profile",
  ], // full access
};