export const ROLES = {
  STUDENT: "student",
  PARENT: "parent",
  TEACHER: "teacher",
  ADMIN: "admin",
  SUPERADMIN: "superadmin",
};

export const ROLE_PERMISSIONS = {
  student: [
    "dashboard",
    "attendance",
    "syllabus",
    "timetable",
    "assignments",
     "fees",
     "library",
    "library-view",
    "hostel",
    "transport",
    "hostel",
    "result",
    "notice",
    "announcement",
    
    "profile",
    
  ],

  parent: [
    "dashboard",
    "attendance",
    "result",
    "fees",
    "notice",
     "announcement",
       "profile",
  ],

  teacher: [
    "dashboard",
    "attendance",
    "syllabus",
    "timetable",
    "assignments",
    "result",
    "notice",
     "library-create",
     "library-view",
     "hostel-view",
     "transport",
     "transport-management",
     "hostel-management",
    "announcement",
    "fees",
    "library",
    "transport",
    "hostel",
      "profile",
  ],

  admin: [
    "dashboard",
 
     "departments",
  "department-list",
  "department-create",
    "user-management",
    "role",
     "academic-assign",
    "academic-data",
    "academic-calendar",
    "academic-timetable",
    "academic-subjects",
    "academic-semester",
    "academic-year",
    "academic-class",
    "academic-program",
    "academic-section",
    "academic-permissions",
    "announcement",
    "announcement-create",
    "notice",
    "fees",
    "library",
    "library-reports",
    "library-create",
    "transport",
    "hostel",
   "users",
  "user-create",
  "user-list",
    "reports",
      "profile",
      "academic-reports",
      "reports",
      "payroll-reports",
      "fee-reports",
      "teacher-payroll",
    "salary-structure",
    "approval",
    "change-request",
    "student-fees",
    "Fees Management",
    "fees-structure",
    "fees-program-map",
    "fees-admin",
  ],

  superadmin: [
     "dashboard",
  "departments",
  "users",
  "user-create",
  "user-list",
  "department-list",
  "department-create",
  "user-management",
  "roles-permissions",
  "reports",
  "billing",
  "audit",
  "organizations",
  "approvals",
  "settings",
  "admins",
  "students",
  "teachers",
  "announcement",
  "announcement-create",
  "notice",
  "profile",
  ], // full access
};